version: "3.8"
services:
  postgres.db:
    container_name: postgres.gym
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: gym
      POSTGRES_USER: gym
      POSTGRES_DB: gym
    networks:
      - gym-net
#    volumes:
#      - ./postgres-volume:/var/lib/postgresql/data

  gin.app:
    container_name: gin.app
#    image: registry.gitlab.com/gym-global/backend/gym:v1
    restart: always
    build:
      context: .
    env_file: .env
    ports:
      - 6000:6000
    depends_on:
      - postgres.db
    networks:
      - gym-net

  redis.cache:
    container_name: redis.redis
    image: redis:6.2.6
    restart: always
    command: redis-server --appendonly yes --requirepass nNS&B#!-,[
    ports:
      - 6379:6379
    networks:
      - gym-net
#    volumes:
#      - ./redis-volume:/data

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /volumes/portainer_data:/data
    networks:
      - gym-net

networks:
  gym-net:

#volumes:
#  redis-volume:
#  postgres-volume: