apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.gym.service: gym-env
  name: gym-env
data:
  ENVIRONMENT: DEV
  GIN_PORT: '6000'
  #POSTGRES_HOST: postgres://gym:gym@postgres:5432/gym?sslmode=disable&binary_parameters=yes
  POSTGRES_HOST: postgres://gym:gym@postgres:5432/gym?sslmode=disable
  # POSTGRES_HOST: postgres://gym:gym@postgres:5432/gym
  POSTGRES_USER: gym
  POSTGRES_PASSWORD: gym
  POSTGRES_DATABASE: gym
  EMAIL_SENDER: ''
  EMAIL_RECEIVERS: ''
  EMAIL_API_KEY: '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'
  REDIS_ADDRESS: redis:6379


