apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.gym.service: gym-app
  name: gym-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.gym.service: gym-app
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.gym.network/app-network: "true"
        io.gym.service: gym-app
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: env
            - name: GIN_PORT
              valueFrom:
                configMapKeyRef:
                  key: GIN_PORT
                  name: env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
          # cloud
          # image: registry.gitlab.com/gym-global/backend/gym:v1
          # local
          image: registry.gitlab.com/gym-global/backend/gym:v1
          name: gin-app
          ports:
            - containerPort: 6000
          resources: {}
      restartPolicy: Always
status: {}
